"use server";

import { revalidatePath } from "next/cache";

import { getMyProfile } from "@/features/academic-identity/actions/get-my-profile";
import { getSupabaseServer } from "@/lib/supabase/server";
import { err, ok, type ActionError, type Result } from "@/lib/result";

import {
  createConversationSchema,
  type CreateConversationInput,
} from "../schemas/chat";

/**
 * Creates an empty conversation row and inserts the student's opening
 * message. The assistant response is generated by the streaming API
 * route — this action only handles the persist.
 *
 * Title = the first ~40 chars of the opening message, so the sidebar
 * shows something meaningful without the student having to name every
 * chat.
 */
export async function createConversation(
  input: CreateConversationInput,
): Promise<Result<{ id: string }, ActionError>> {
  const parsed = createConversationSchema.safeParse(input);
  if (!parsed.success) {
    return err({
      code: "VALIDATION",
      message: "Please check your message.",
      fieldErrors: parsed.error.flatten().fieldErrors,
    });
  }

  const profile = await getMyProfile();
  if (!profile) return err({ code: "FORBIDDEN", message: "Complete onboarding first." });

  const subjectId = parsed.data.subjectId ?? null;
  if (subjectId && !profile.subjects.some((s) => s.id === subjectId)) {
    return err({
      code: "VALIDATION",
      message: "Pick a subject from your profile.",
      fieldErrors: { subjectId: ["Not in your active subjects"] },
    });
  }

  const supabase = await getSupabaseServer();
  const trimmed = parsed.data.firstMessage.trim();
  const title = trimmed.length > 40 ? `${trimmed.slice(0, 37)}…` : trimmed;

  const insertRes = await supabase
    .from("chat_conversations")
    .insert({
      user_id: profile.userId,
      subject_id: subjectId,
      title,
    })
    .select("id")
    .single();

  if (insertRes.error || !insertRes.data) {
    // Surface the underlying Postgres error so a missing migration
    // (e.g. `chat_conversations` doesn't exist in prod Supabase) or an
    // RLS block shows the actual reason instead of a generic toast.
    const detail = insertRes.error?.message ?? "unknown error";
    console.error("[createConversation] insert failed", {
      code: insertRes.error?.code,
      message: insertRes.error?.message,
      hint: insertRes.error?.hint,
    });
    return err({
      code: "DB",
      message: `Couldn't start the chat: ${detail}`,
    });
  }

  const conversationId = insertRes.data.id;

  const { error: msgErr } = await supabase.from("chat_messages").insert({
    conversation_id: conversationId,
    user_id: profile.userId,
    role: "user",
    content: trimmed,
  });

  if (msgErr) {
    await supabase.from("chat_conversations").delete().eq("id", conversationId);
    console.error("[createConversation] message insert failed", {
      code: msgErr.code,
      message: msgErr.message,
    });
    return err({
      code: "DB",
      message: `Couldn't save your message: ${msgErr.message}`,
    });
  }

  revalidatePath("/app/chat");
  return ok({ id: conversationId });
}
